project:
  type: book

book:
  title: "Mastering Communication Between Shiny Modules"
  author: "Philippe Peret"
  date: today
  sidebar: 
    footer: "</br>[![](image/by-nc-sa.png){height=42px}](https://creativecommons.org/licenses/by-nc-sa/4.0/)"
  chapters:
    - index.qmd
    - introduction.qmd
    - part: "Communication Foundations"
      chapters: 
      - communication-inside-module.qmd
      - communication-from-module.qmd
      - communication-to-module.qmd
      - communication-between-modules.qmd
    - part: "Extending beyond basics"
      chapters: 
      - ui-server.qmd
      - considerations-parameters-return-values.qmd
      - complex-objects.qmd
      - complex-instructions.qmd
    - part: "Architecture & Best Practices"
      chapters: 
      - architecture-thinking.qmd
      - communication-manifest.qmd
    - conclusion.qmd
    - references.qmd
  appendices:
    - resources.qmd
  page-footer:
    border: false
    left: "Copyright 2025, Philippe Peret" 
    right: 
      - icon: github
        href: https://github.com/thekangaroofactory
        target: _blank
      - icon: linkedin 
        href: https://www.linkedin.com/in/philippeperet/
        target: _blank

bibliography: references.bib

format:
  html:
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/'
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

