project:
  type: book

book:
  title: "Mastering Communication Between Shiny Modules"
  author: "Philippe Peret"
  date: today
  chapters:
    - index.qmd
    - intro.qmd
    - communication-inside-module.qmd
    - communication-from-module.qmd
    - communication-to-module.qmd
    - communication-between-modules.qmd
    - ui-server.qmd
    - considerations-parameters-return-values.qmd
    - complex-objects.qmd
    - complex-instructions.qmd
    - communication-manifest.qmd
    - references.qmd
  page-footer:
    border: false
    left: "Copyright 2025, Philippe Peret" 
    right: 
      - icon: github
        href: https://github.com/thekangaroofactory
      - icon: linkedin 
        href: https://www.linkedin.com/in/philippeperet/

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

