# Resources

The following material is provided and accessible so that you can use this guide in a practical context.

## GitHub repository

A repository on GitHub is available with templates to support this book.

<https://github.com/thekangaroofactory/template-r-shiny-communication>

## Repository folders

Each folder inside the GitHub repository is attached to a specific chapter in this book.

### Communication Foundations

#### Communication inside module

-   [module-input](https://github.com/thekangaroofactory/template-r-shiny-communication/tree/main/module-input)

-    [module-output](https://github.com/thekangaroofactory/template-r-shiny-communication/tree/main/module-output)

#### Communication from a module (to its parent)

-   [module-return-value](https://github.com/thekangaroofactory/template-r-shiny-communication/tree/main/module-return-value)

#### Communication to the module (from it’s parent)

-   [module-parameter](https://github.com/thekangaroofactory/template-r-shiny-communication/tree/main/module-parameter)

#### Communication between modules

-   [module-nested-input](https://github.com/thekangaroofactory/template-r-shiny-communication/tree/main/module-nested-input)

-   [module-nested-output](https://github.com/thekangaroofactory/template-r-shiny-communication/tree/main/module-nested-output)

-   [module-nested-parameter](https://github.com/thekangaroofactory/template-r-shiny-communication/tree/main/module-nested-parameter)

-   [module-nested-return-value](https://github.com/thekangaroofactory/template-r-shiny-communication/tree/main/module-nested-return-value)

-   [module-siblings-input](https://github.com/thekangaroofactory/template-r-shiny-communication/tree/main/module-siblings-input)

-   [module-siblings-output](https://github.com/thekangaroofactory/template-r-shiny-communication/tree/main/module-siblings-output)

-   [module-siblings-communication](https://github.com/thekangaroofactory/template-r-shiny-communication/tree/main/module-siblings-communication)

### Extending beyond basics

#### UI vs Server sides

-   [ui-server](https://github.com/thekangaroofactory/template-r-shiny-communication/tree/main/ui-server)

#### Additional considerations for parameters & return values

-   [additional-considerations](https://github.com/thekangaroofactory/template-r-shiny-communication/tree/main/additional-considerations)

#### Building complex communication objects

-   [complex-values](https://github.com/thekangaroofactory/template-r-shiny-communication/tree/main/complex-values)

#### Building complex input instructions

-   [complex-instructions](https://github.com/thekangaroofactory/template-r-shiny-communication/tree/main/complex-instructions)

### Architecture & Best Practices \<\< a priori rien

#### Wrapup

-   [wrapup-module](https://github.com/thekangaroofactory/template-r-shiny-communication/tree/main/wrapup-module) ?? – cité nulle part ??
